version: "3.3"

services:
  app:
    build:
      context: .
    hostname: app
    ports:
      - "3001:3001"
    volumes:
      - ./app:/app
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - dev-db-data:/var/mongo/data
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

    depends_on:
      - mongo

  redis:
    image: 'redis:7.0-alpine'
    hostname: redis
    ports:
      - 6379:6379

volumes:
  dev-db-data:


